#!/usr/bin/env python3
"""Compile the hardware renderer's shaders (src/app/gpu/*.hlsl) for every
SDL_GPU backend and write src/app/gpu/shaders_gen.h, which is committed: a
build needs no shader tools, only changing a shader does.

  build_shaders.py

DXC compiles the HLSL to SPIR-V (Vulkan) and DXIL (Direct3D 12); SPIRV-Cross
turns the SPIR-V into MSL (Metal). With dxc and spirv-cross on PATH they run
here; otherwise in Docker (Ubuntu 24.04, DXC's pinned Linux release, the
distribution's spirv-cross). Both are tools only, not part of the game.
"""

import os
import shutil
import subprocess
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = "src/app/gpu/m2.hlsl"
OUT = os.path.join(ROOT, "src", "app", "gpu", "shaders_gen.h")
WORK = "build/shaders"
DXC_URL = ("https://github.com/microsoft/DirectXShaderCompiler/releases/download/"
           "v1.9.2609/linux_dxc_2026_09_28.x86_x64.tar.gz")

# entry point, shader stage, profile
ENTRIES = [("vs_poly", "vertex", "vs_6_0"), ("ps_poly", "fragment", "ps_6_0"),
           ("vs_quad", "vertex", "vs_6_0"), ("ps_quad", "fragment", "ps_6_0"),
           ("ps_tiles_back", "fragment", "ps_6_0"), ("ps_tiles_front", "fragment", "ps_6_0")]


def commands(dxc, spirv_cross):
    cmds = [f"mkdir -p {WORK}"]
    for entry, _, profile in ENTRIES:
        base = f"{WORK}/{entry}"
        cmds += [
            f"{dxc} -spirv -fspv-target-env=vulkan1.0 -fspv-entrypoint-name=main -T {profile} -E {entry} -Fo {base}.spv {SRC}",
            f"{dxc} -T {profile} -E {entry} -Fo {base}.dxil {SRC}",
            f"{spirv_cross} {base}.spv --msl --msl-version 20100 --output {base}.metal",
        ]
    return cmds


def main():
    if shutil.which("dxc") and shutil.which("spirv-cross"):
        os.makedirs(os.path.join(ROOT, WORK), exist_ok=True)
        for entry, _, profile in ENTRIES:
            base = f"{WORK}/{entry}"
            subprocess.run(["dxc", "-spirv", "-fspv-target-env=vulkan1.0", "-fspv-entrypoint-name=main",
                            "-T", profile, "-E", entry, "-Fo", base + ".spv", SRC], check=True, cwd=ROOT)
            subprocess.run(["dxc", "-T", profile, "-E", entry, "-Fo", base + ".dxil", SRC], check=True, cwd=ROOT)
            subprocess.run(["spirv-cross", base + ".spv", "--msl", "--msl-version", "20100",
                            "--output", base + ".metal"], check=True, cwd=ROOT)
    else:
        if not shutil.which("docker"):
            sys.exit("build_shaders: needs dxc and spirv-cross on PATH, or Docker")
        script = " && ".join([
            "apt-get update -qq",
            "apt-get install -y -qq curl ca-certificates spirv-cross > /dev/null",
            f"curl -sSL -o /tmp/dxc.tgz {DXC_URL}",
            "mkdir -p /tmp/dxc && tar xzf /tmp/dxc.tgz -C /tmp/dxc",
            "export LD_LIBRARY_PATH=/tmp/dxc/lib",
        ] + commands("/tmp/dxc/bin/dxc", "spirv-cross"))
        # DXC's Linux build is x86-64. Pull that variant explicitly: a cached
        # arm64 ubuntu:24.04 (Apple silicon) otherwise fails with "exec format error".
        subprocess.run(["docker", "pull", "-q", "--platform", "linux/amd64", "ubuntu:24.04"], check=True)
        subprocess.run(["docker", "run", "--rm", "--platform", "linux/amd64", "-v", f"{ROOT}:/src", "-w", "/src",
                        "ubuntu:24.04", "bash", "-c", script], check=True)

    def bytes_array(name, data):
        rows = [", ".join(f"0x{b:02x}" for b in data[i:i + 16]) for i in range(0, len(data), 16)]
        return f"static const unsigned char {name}[] = {{\n    " + ",\n    ".join(rows) + "\n};\n"

    def string_literal(name, text):
        body = text.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n\"\n    \"")
        return f"static const char {name}[] =\n    \"{body}\";\n"

    out = ["// Generated by scripts/build_shaders.py from src/app/gpu/m2.hlsl: do not edit.",
           "#pragma once", ""]
    for entry, _, _ in ENTRIES:
        base = os.path.join(ROOT, WORK, entry)
        out.append(bytes_array(f"k_{entry}_spv", open(base + ".spv", "rb").read()))
        out.append(bytes_array(f"k_{entry}_dxil", open(base + ".dxil", "rb").read()))
        out.append(string_literal(f"k_{entry}_msl", open(base + ".metal").read()))
    open(OUT, "w").write("\n".join(out))
    print(f"build_shaders: wrote {os.path.relpath(OUT, ROOT)}")


if __name__ == "__main__":
    main()
